### ISSUE TITLE
Not an Issue but a Question

### ISSUE THREAD

**Issue by bigredsmokehouse** [skyeperry1/Arduino_Meat_Probe_Library#2]
I have no problem writing code but I am learning the arduino hardware interfaces.  I am going to leverage your nice simple Maverick probe interface.  I built one using the Max31855 breakout board but I wanted to use the Maverick probe.  I am planning on using your interface with 2 probes, PID controller, 4x20 LCD for the UI , Servo motor and selenoids to drive the propane control.  The first implementation will be using an on/off PID algorithm.

Sorry for such as silly question but the 2.5mm mono jacks seem to be 3 terminals as standard (TSR).  I have never worked with this hardware.  Can you be more specific as far as the connections between the jack and the breadboard (mainly the tip, ring or sleeve)?  

Thanks in advance and I am looking forward to expanding your prototype.

**Comment by skyeperry1** [comment]
bigredsmokehouse, 
Glad to hear that your using this. The probes are only t/s so you'll only need a mono jack. most of the mono jacks that I was able to find were 3 prong. You only need to use 2 of the pins on the 2.5mm jack. 2 of the pins on the jack will be connected, Just check with the multimeter to find the 2 pins that are connected and bend down the extra pin.
